# Generated by Django 5.1.3 on 2024-11-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
